sudo: required
services:
  - docker
  
before_install:
  - docker build -t max/react-test -f Dockerfile.dev -f ./client/Dockerfile.dev ./client
  
script:
  - docker run -e CI=true max/react-test npm run test -- --coverage


after_success:
  - docker build -t max/multi-client ./client
  - docker build -t max/multi-nginx ./nginx
  - docker build -t max/multi-server ./server
  - docker build -t max/multi-worker ./worker
