name: deploy to GKE

on:
  push:
    branches:
      - 'master'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Build client tests
        run: |-
          docker build -t makc1902/react-test -f ./client/Dockerfile.dev ./client
      -
        name: Run client tests
        run: docker run -e CI=true makc1902/react-test npm test
  
  build-and-push:
    needs: tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          -
            context: 'client'
            image: 'multi-client'
          -
            context: 'server'
            image: 'multi-server'
          -
            context: 'worker'
            image: 'multi-worker'

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      - 
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Build
        run: |-
          docker build \
            -t makc1902/${{ matrix.image }}:latest \
            -t makc1902/${{ matrix.image }}:${{ github.sha }} \
            -f ./${{ matrix.context }}/Dockerfile \
            ./${{ matrix.context }}
      
      -
        name: Push
        run: docker push makc1902/${{ matrix.image }}:${{ github.sha }}
